import type { Certificate } from "./types";

/**
 * Certificate Center data (§12.1). Every certificate shows entity, scope,
 * validity and status — never a bare logo wall (§7.7, §12).
 * All records below are ILLUSTRATIVE placeholders: numbers, dates and scopes
 * must be replaced with the real certificates before production.
 */
export const certificates: Certificate[] = [
  {
    id: "haccp-daklak",
    scheme: "HACCP (Codex Alimentarius)",
    schemeShort: "HACCP",
    entity: "Buon Ma Thuot Coffee Processing Plant",
    facilityId: "dak-lak-coffee-plant",
    scope: "Cleaning, grading, sorting and packing of green coffee and black pepper",
    products: ["coffee", "pepper"],
    number: "HACCP-XXXX-0001",
    issued: "2025-11-12",
    expires: "2028-11-11",
    status: "valid",
    documentId: "cert-haccp-daklak",
    claimRule: "May state “HACCP-certified facility” on pages for coffee and pepper processed at this plant only.",
    verified: false,
  },
  {
    id: "ra-coffee-group",
    scheme: "Rainforest Alliance (Farm & Supply Chain)",
    schemeShort: "Rainforest Alliance",
    entity: "Dak Lak farmer group [group name] + Buon Ma Thuot plant (CoC)",
    facilityId: "dak-lak-coffee-plant",
    scope: "Robusta coffee from certified farmer group; supply-chain certificate for handling",
    products: ["coffee"],
    number: "RA-XXXX-0002",
    issued: "2025-06-30",
    expires: "2027-06-29",
    status: "valid",
    documentId: "cert-ra-coffee",
    verificationUrl: "https://www.rainforest-alliance.org/",
    claimRule: "Claim only on lots sold as certified with transaction record; not a company-wide claim. Seal use requires approval.",
    verified: false,
  },
  {
    id: "halal-daklak",
    scheme: "Halal certification",
    schemeShort: "Halal",
    entity: "Buon Ma Thuot Coffee Processing Plant",
    facilityId: "dak-lak-coffee-plant",
    scope: "Green coffee and black pepper",
    products: ["coffee", "pepper"],
    number: "HL-XXXX-0003",
    issued: "2025-10-01",
    expires: "2026-10-20",
    status: "renewal-pending",
    documentId: "cert-halal-daklak",
    claimRule: "Display with the issuing body name and expiry. Hide claim automatically if expired.",
    verified: false,
  },
  {
    id: "brcgs-cashew",
    scheme: "BRCGS Food Safety (Issue 9)",
    schemeShort: "BRCGS",
    entity: "Dong Xoai Cashew Processing Plant",
    facilityId: "binh-phuoc-cashew-plant",
    scope: "Processing, grading and vacuum packing of raw and roasted cashew kernels",
    products: ["cashew"],
    number: "BRC-XXXX-0004",
    issued: "2026-02-18",
    expires: "2027-03-31",
    status: "valid",
    documentId: "cert-brcgs-cashew",
    verificationUrl: "https://www.brcgs.com/",
    claimRule: "State grade and scope as listed in the BRCGS directory. Logo use per BRCGS logo rules.",
    verified: false,
  },
  {
    id: "iso22000-cashew",
    scheme: "ISO 22000:2018",
    schemeShort: "ISO 22000",
    entity: "Dong Xoai Cashew Processing Plant",
    facilityId: "binh-phuoc-cashew-plant",
    scope: "Food safety management for cashew kernel processing",
    products: ["cashew"],
    number: "ISO-XXXX-0005",
    issued: "2024-08-01",
    expires: "2027-07-31",
    status: "valid",
    documentId: "cert-iso-cashew",
    claimRule: "“ISO 22000 certified” applies to the cashew plant only.",
    verified: false,
  },
  {
    id: "kosher-cashew",
    scheme: "Kosher certification",
    schemeShort: "Kosher",
    entity: "Dong Xoai Cashew Processing Plant",
    facilityId: "binh-phuoc-cashew-plant",
    scope: "Raw cashew kernels (whole and splits)",
    products: ["cashew"],
    issued: "2025-12-01",
    expires: "2026-11-30",
    status: "valid",
    documentId: "cert-kosher-cashew",
    claimRule: "Letter of certification per product list; roasted lines not covered.",
    verified: false,
  },
  {
    id: "haccp-cantho",
    scheme: "HACCP (Codex Alimentarius)",
    schemeShort: "HACCP",
    entity: "Can Tho Rice Milling & Packing Plant",
    facilityId: "can-tho-rice-mill",
    scope: "Milling, sorting and packing of white and fragrant rice",
    products: ["rice"],
    number: "HACCP-XXXX-0007",
    issued: "2025-04-15",
    expires: "2028-04-14",
    status: "valid",
    documentId: "cert-haccp-cantho",
    claimRule: "Applies to rice packed at the Can Tho plant.",
    verified: false,
  },
  {
    id: "brcgs-rice",
    scheme: "BRCGS Food Safety (Issue 9)",
    schemeShort: "BRCGS",
    entity: "Can Tho Rice Milling & Packing Plant",
    facilityId: "can-tho-rice-mill",
    scope: "Rice retail packing line (1–5 kg)",
    products: ["rice"],
    number: "BRC-XXXX-0008",
    issued: "2025-01-10",
    expires: "2026-03-31",
    status: "expired",
    documentId: "cert-brcgs-rice",
    claimRule: "Expired — must not be claimed on product or marketing pages until renewed.",
    verified: false,
  },
  {
    id: "globalgap-dragonfruit",
    scheme: "GLOBALG.A.P. IFA (Option 2 – producer group)",
    schemeShort: "GLOBALG.A.P.",
    entity: "Binh Thuan dragon fruit producer group [group name]",
    scope: "Dragon fruit — listed member farms only (GGN on certificate)",
    products: ["fruits"],
    number: "GGN XXXX XXXX XXXXX",
    issued: "2026-05-20",
    expires: "2027-05-19",
    status: "valid",
    documentId: "cert-globalgap-dragonfruit",
    verificationUrl: "https://globalgap.org/ggn/",
    claimRule: "Use the GGN and certificate scope; do not imply all fruit is certified. GGN label only for eligible products.",
    verified: false,
  },
  {
    id: "organic-pepper",
    scheme: "EU Organic (Regulation (EU) 2018/848)",
    schemeShort: "EU Organic",
    entity: "Gia Lai pepper grower group [group name]",
    scope: "Black pepper — organic grower group and handling",
    products: ["pepper"],
    number: "VN-BIO-XXX-0010",
    issued: "2025-09-01",
    expires: "2026-08-31",
    status: "expired",
    documentId: "cert-organic-pepper",
    claimRule: "Expired — organic claim removed until the renewed certificate is uploaded.",
    verified: false,
  },
];
