import type { Facility } from "./types";

/** Facilities — every metric carries the definition that must be confirmed before publishing (§11). */
export const facilities: Facility[] = [
  {
    id: "dak-lak-coffee-plant",
    name: "Buon Ma Thuot Coffee Processing Plant",
    shortName: "Coffee plant · Dak Lak",
    type: "Green coffee & pepper processing",
    address: "[Verified address], Buon Ma Thuot, Dak Lak, Vietnam",
    province: "Dak Lak",
    portDistance: "≈ 350 km to Cat Lai / Cai Mep",
    products: ["coffee", "pepper"],
    metrics: [
      { id: "area", value: "32,000 m²", label: "Facility area", definition: "Site area of this facility only", verified: false },
      { id: "capacity", value: "60,000 MT", label: "Annual capacity", definition: "Green coffee, nameplate, per year", verified: false },
      { id: "lines", value: "4", label: "Processing lines", definition: "Commissioned cleaning / grading lines", verified: false },
      { id: "warehouse", value: "20,000 MT", label: "Warehouse", definition: "Bagged storage capacity, ambient", verified: false },
    ],
    processes: [
      { title: "Intake & sampling", body: "Moisture and defect sampling on every truck before unloading." },
      { title: "Cleaning & destoning", body: "Pre-cleaner, destoner and magnet remove foreign matter." },
      { title: "Screen grading", body: "Gravity separation and screen sizing to buyer spec (S13–S18)." },
      { title: "Optical sorting", body: "Colour sorters remove black, broken and discoloured beans." },
      { title: "Polishing (optional)", body: "Wet-polishing for buyers who require it." },
      { title: "Bagging & loading", body: "Jute or bulk-liner loading with lot marks and seal records." },
    ],
    equipment: ["Colour sorters", "Gravity tables", "Screen graders", "Moisture analysers", "Container bulk-liner loading"],
    certificateIds: ["haccp-daklak", "ra-coffee-group", "halal-daklak"],
    image: { kind: "factory", alt: "Coffee processing line with colour sorters", caption: "Factory – grading & sorting line" },
    gallery: [
      { src: "/images/coffee/beans-scoop.jpg", kind: "product", motif: "bean", alt: "Coffee beans in a scoop and jute sack", focal: "80% 50%" },
      { kind: "logistics", alt: "Container loading of jute bags", caption: "Loading – 20 ft container" },
    ],
    verified: false,
  },
  {
    id: "binh-phuoc-cashew-plant",
    name: "Dong Xoai Cashew Processing Plant",
    shortName: "Cashew plant · Dong Nai",
    type: "Cashew shelling, peeling & grading",
    address: "[Verified address], Dong Xoai, Dong Nai, Vietnam",
    province: "Dong Nai (former Binh Phuoc)",
    portDistance: "≈ 110 km to Cat Lai",
    products: ["cashew"],
    metrics: [
      { id: "area", value: "18,500 m²", label: "Facility area", definition: "Site area of this facility only", verified: false },
      { id: "capacity", value: "12,000 MT", label: "Annual capacity", definition: "Kernel output, per year", verified: false },
      { id: "lines", value: "3", label: "Processing lines", definition: "Shelling + peeling lines commissioned", verified: false },
      { id: "cold", value: "0 – 5 °C", label: "Cold storage", definition: "Kernel storage temperature range", verified: false },
    ],
    processes: [
      { title: "RCN intake", body: "Outturn (KOR) and moisture test for each raw-nut lot." },
      { title: "Steaming & shelling", body: "Automatic shelling lines with controlled steaming." },
      { title: "Drying & peeling", body: "Kernel drying to target moisture, then peeling." },
      { title: "Grading", body: "Size and colour grading to W180 – W450 and splits." },
      { title: "Metal detection", body: "Every carton passes a calibrated metal detector." },
      { title: "Vacuum packing", body: "Tins or bags, CO₂ flushed, lot-coded." },
    ],
    equipment: ["Automatic shelling machines", "Peeling lines", "Optical graders", "Metal detectors", "Vacuum packers"],
    certificateIds: ["brcgs-cashew", "iso22000-cashew", "kosher-cashew"],
    image: { kind: "factory", alt: "Cashew kernel grading tables", caption: "Factory – kernel grading" },
    gallery: [
      { src: "/images/cashew/basket.jpg", kind: "product", motif: "kernel", alt: "Graded white cashew kernels" },
      { kind: "factory", alt: "Cold storage", caption: "Cold storage – kernels" },
    ],
    verified: false,
  },
  {
    id: "dong-thap-fruit-plant",
    name: "Dong Thap Dried Fruit Processing Plant",
    shortName: "Dried fruit plant · Dong Thap",
    type: "Mango ripening, slicing, drying & packing",
    address: "[Verified address], Cao Lanh, Dong Thap, Vietnam",
    province: "Dong Thap",
    portDistance: "≈ 150 km to Cat Lai",
    products: ["mango"],
    metrics: [
      { id: "area", value: "12,000 m²", label: "Facility area", definition: "Site area of this facility only", verified: false },
      { id: "capacity", value: "1,800 MT", label: "Annual capacity", definition: "Finished dried mango, per year", verified: false },
      { id: "lines", value: "2", label: "Drying lines", definition: "Commissioned slicing + drying lines", verified: false },
      { id: "warehouse", value: "18 – 22 °C", label: "Finished-goods store", definition: "Temperature-controlled storage for packed product", verified: false },
    ],
    processes: [
      { title: "Fruit intake", body: "Brix, ripeness and defect checks on every orchard delivery." },
      { title: "Ripening & washing", body: "Controlled ripening, washing and sanitising before peeling." },
      { title: "Peeling & slicing", body: "Hand peeling and slicing to the specified thickness." },
      { title: "Infusion & drying", body: "Light syrup infusion (per spec) and low-temperature drying to target moisture." },
      { title: "Inspection", body: "Moisture and water activity checks, metal detection on every pack." },
      { title: "Packing", body: "Bulk cartons or Owi Chewi / private-label pouches, lot-coded." },
    ],
    equipment: ["Ripening rooms", "Slicing tables", "Hot-air drying tunnels", "Water activity meter", "Metal detectors", "Pouch filling & sealing"],
    certificateIds: ["haccp-dongthap", "brcgs-mango"],
    image: { kind: "factory", alt: "Dried mango drying tunnels", caption: "Factory – drying tunnels" },
    gallery: [
      { src: "/images/mango/bowl-1.jpg", kind: "product", motif: "fruit", alt: "Owi Chewi soft dried mango" },
      { kind: "factory", alt: "Pouch packing line", caption: "Packing – Owi Chewi pouches" },
    ],
    verified: false,
  },
];
