import type { Facility } from "./types";

/** Facilities — every metric carries the definition that must be confirmed before publishing (§11). */
export const facilities: Facility[] = [
  {
    id: "dak-lak-coffee-plant",
    name: "Buon Ma Thuot Coffee Processing Plant",
    shortName: "Coffee plant · Dak Lak",
    type: "Green coffee & pepper processing",
    address: "[Verified address], Buon Ma Thuot, Dak Lak, Vietnam",
    province: "Dak Lak",
    portDistance: "≈ 350 km to Cat Lai / Cai Mep",
    products: ["coffee", "pepper"],
    metrics: [
      { id: "area", value: "32,000 m²", label: "Facility area", definition: "Site area of this facility only", verified: false },
      { id: "capacity", value: "60,000 MT", label: "Annual capacity", definition: "Green coffee, nameplate, per year", verified: false },
      { id: "lines", value: "4", label: "Processing lines", definition: "Commissioned cleaning / grading lines", verified: false },
      { id: "warehouse", value: "20,000 MT", label: "Warehouse", definition: "Bagged storage capacity, ambient", verified: false },
    ],
    processes: [
      { title: "Intake & sampling", body: "Moisture and defect sampling on every truck before unloading." },
      { title: "Cleaning & destoning", body: "Pre-cleaner, destoner and magnet remove foreign matter." },
      { title: "Screen grading", body: "Gravity separation and screen sizing to buyer spec (S13–S18)." },
      { title: "Optical sorting", body: "Colour sorters remove black, broken and discoloured beans." },
      { title: "Polishing (optional)", body: "Wet-polishing for buyers who require it." },
      { title: "Bagging & loading", body: "Jute or bulk-liner loading with lot marks and seal records." },
    ],
    equipment: ["Colour sorters", "Gravity tables", "Screen graders", "Moisture analysers", "Container bulk-liner loading"],
    certificateIds: ["haccp-daklak", "ra-coffee-group", "halal-daklak"],
    image: { kind: "factory", alt: "Coffee processing line with colour sorters", caption: "Factory – grading & sorting line" },
    gallery: [
      { kind: "factory", alt: "Bagged coffee warehouse", caption: "Warehouse – bagged lots" },
      { kind: "logistics", alt: "Container loading of jute bags", caption: "Loading – 20 ft container" },
    ],
    verified: false,
  },
  {
    id: "binh-phuoc-cashew-plant",
    name: "Dong Xoai Cashew Processing Plant",
    shortName: "Cashew plant · Dong Nai",
    type: "Cashew shelling, peeling & grading",
    address: "[Verified address], Dong Xoai, Dong Nai, Vietnam",
    province: "Dong Nai (former Binh Phuoc)",
    portDistance: "≈ 110 km to Cat Lai",
    products: ["cashew"],
    metrics: [
      { id: "area", value: "18,500 m²", label: "Facility area", definition: "Site area of this facility only", verified: false },
      { id: "capacity", value: "12,000 MT", label: "Annual capacity", definition: "Kernel output, per year", verified: false },
      { id: "lines", value: "3", label: "Processing lines", definition: "Shelling + peeling lines commissioned", verified: false },
      { id: "cold", value: "0 – 5 °C", label: "Cold storage", definition: "Kernel storage temperature range", verified: false },
    ],
    processes: [
      { title: "RCN intake", body: "Outturn (KOR) and moisture test for each raw-nut lot." },
      { title: "Steaming & shelling", body: "Automatic shelling lines with controlled steaming." },
      { title: "Drying & peeling", body: "Kernel drying to target moisture, then peeling." },
      { title: "Grading", body: "Size and colour grading to W180 – W450 and splits." },
      { title: "Metal detection", body: "Every carton passes a calibrated metal detector." },
      { title: "Vacuum packing", body: "Tins or bags, CO₂ flushed, lot-coded." },
    ],
    equipment: ["Automatic shelling machines", "Peeling lines", "Optical graders", "Metal detectors", "Vacuum packers"],
    certificateIds: ["brcgs-cashew", "iso22000-cashew", "kosher-cashew"],
    image: { kind: "factory", alt: "Cashew kernel grading tables", caption: "Factory – kernel grading" },
    gallery: [
      { kind: "factory", alt: "Vacuum packing room", caption: "Packing – vacuum cartons" },
      { kind: "factory", alt: "Cold storage", caption: "Cold storage – kernels" },
    ],
    verified: false,
  },
  {
    id: "can-tho-rice-mill",
    name: "Can Tho Rice Milling & Packing Plant",
    shortName: "Rice mill · Can Tho",
    type: "Rice milling, sorting & packing",
    address: "[Verified address], Can Tho, Vietnam",
    province: "Can Tho",
    portDistance: "≈ 170 km to Cat Lai · river barge available",
    products: ["rice", "fruits"],
    metrics: [
      { id: "area", value: "25,000 m²", label: "Facility area", definition: "Site area of this facility only", verified: false },
      { id: "capacity", value: "150,000 MT", label: "Annual capacity", definition: "Milled rice, per year", verified: false },
      { id: "lines", value: "2", label: "Milling lines", definition: "Commissioned milling + sorting lines", verified: false },
      { id: "warehouse", value: "30,000 MT", label: "Warehouse", definition: "Paddy + milled rice storage", verified: false },
    ],
    processes: [
      { title: "Paddy intake", body: "Moisture, variety and purity checks per barge." },
      { title: "Drying", body: "Controlled drying to safe storage moisture." },
      { title: "Husking & whitening", body: "Milling to the specified degree of polish." },
      { title: "Sorting", body: "Length grading and colour sorting to broken % target." },
      { title: "Packing", body: "25–50 kg bulk or 1–5 kg retail / private label." },
    ],
    equipment: ["Dryers", "Whitening & polishing", "Length graders", "Colour sorters", "Auto-weighing packers"],
    certificateIds: ["haccp-cantho", "brcgs-rice"],
    image: { kind: "factory", alt: "Rice mill polishing line", caption: "Factory – milling & polishing" },
    gallery: [
      { kind: "factory", alt: "Retail rice packing line", caption: "Packing – private label" },
      { kind: "logistics", alt: "River barge with paddy", caption: "Logistics – river barge" },
    ],
    verified: false,
  },
];
