import type { Insight } from "./types";

/*
 * Buyer resource center (§15). Articles serve procurement and international
 * SEO; corporate news is secondary. Figures in articles are illustrative and
 * market/regulatory updates must be reviewed by compliance before publishing.
 */
export const insights: Insight[] = [
  {
    slug: "vietnam-robusta-crop-outlook-2026-27",
    title: "Vietnam robusta crop outlook 2026/27: what buyers should plan for",
    pillar: "Crop outlook",
    summary:
      "Flowering, rainfall and farmer selling behaviour in the Central Highlands — and what they mean for contract timing and screen-size availability.",
    publishedAt: "2026-09-22",
    readingMinutes: 6,
    reviewedBy: "Coffee desk · QA",
    relatedProducts: ["robusta-grade-1-screen-16", "robusta-grade-1-screen-18", "robusta-grade-2-screen-13"],
    cta: { label: "Download Robusta S16 specification", href: "/api/documents/spec-robusta-grade-1-screen-16" },
    image: { kind: "origin", alt: "Coffee farms in Dak Lak before harvest", caption: "Aerial – Dak Lak before harvest" },
    body: [
      { type: "p", text: "The 2026/27 harvest in the Central Highlands begins in late October at lower altitudes and peaks from November to January. This outlook summarises field observations from our sourcing team and what they imply for buyers planning Q4 2026 – Q2 2027 shipments." },
      { type: "h2", text: "Field observations" },
      { type: "ul", items: ["Flowering in Dak Lak and Gia Lai was even after timely irrigation in March–April.", "Rainy-season rainfall was close to average; cherry development looks uniform.", "Farmers continue to intercrop with durian and pepper, which affects labour availability at peak harvest."] },
      { type: "h2", text: "What this means for screen sizes" },
      { type: "p", text: "Uniform cherry development usually improves the share of Screen 16 and above. Buyers who need S18 wet-polished should still book early: large-bean lots are separated at the plant and volumes are limited per crop." },
      { type: "table", head: ["Grade", "Availability outlook", "Recommendation"], rows: [["G1 S18", "Limited", "Contract Oct–Nov for Dec–Feb shipment"], ["G1 S16", "Good", "Flexible; book 4–6 weeks ahead"], ["G2 S13", "Good", "Spot or rolling contracts"]] },
      { type: "note", text: "Figures and assessments in this article are illustrative for the website preview and must be replaced with the sourcing team's reviewed outlook before publishing." },
      { type: "h2", text: "Planning checklist" },
      { type: "ul", items: ["Confirm your type sample before harvest so pre-shipment samples can be matched.", "Agree moisture limit and polishing requirement in the contract.", "For EU shipments, confirm which due-diligence information you need from us (see EUDR information pack)."] },
    ],
  },
  {
    slug: "robusta-screen-size-guide",
    title: "Robusta screen sizes explained: S13, S16, S18 and what they mean for your roast",
    pillar: "Product education",
    summary: "How screen size is measured, why it matters for roasting consistency, and how to read a green coffee specification.",
    publishedAt: "2026-08-18",
    readingMinutes: 5,
    reviewedBy: "QA laboratory",
    relatedProducts: ["robusta-grade-1-screen-16", "robusta-grade-1-screen-18", "robusta-grade-2-screen-13"],
    cta: { label: "View robusta grades", href: "/products/coffee" },
    image: { kind: "product", motif: "bean", alt: "Coffee beans on grading sieves", caption: "Macro – sieve analysis" },
    body: [
      { type: "p", text: "Screen size is the diameter of the round holes a bean does not pass through, measured in 64ths of an inch. A Screen 16 bean is retained on a sieve with 16/64-inch (6.35 mm) holes." },
      { type: "h2", text: "Why buyers specify screen size" },
      { type: "ul", items: ["Uniform size roasts more evenly — fewer scorched small beans.", "Larger screens usually carry a price premium.", "Soluble plants care more about yield and defects than size."] },
      { type: "h2", text: "How to read “90% on S16”" },
      { type: "p", text: "A specification of “Screen 16+, min. 90% on S16” means at least 90% of the sample by weight is retained on a 16 screen. The remaining 10% may pass to smaller screens but not below the stated tolerance." },
      { type: "table", head: ["Screen", "Hole size", "Typical use"], rows: [["S13", "5.16 mm", "Soluble, value blends"], ["S16", "6.35 mm", "Mainstream roasting"], ["S18", "7.14 mm", "Premium, espresso"]] },
    ],
  },
  {
    slug: "documents-for-importing-vietnamese-fruit",
    title: "Documents for importing fresh Vietnamese fruit: a buyer's checklist",
    pillar: "Import guide",
    summary: "Phytosanitary requirements, growing-area codes and treatment rules differ by commodity and destination. Here is how to check before you contract.",
    publishedAt: "2026-07-30",
    readingMinutes: 7,
    reviewedBy: "Compliance",
    relatedProducts: ["white-flesh-dragon-fruit", "cat-chu-mango", "frozen-durian-ri6"],
    cta: { label: "Ask our fresh fruit desk", href: "/contact?topic=fresh-fruit" },
    image: { kind: "logistics", alt: "Reefer containers at port", caption: "Logistics – reefer yard" },
    body: [
      { type: "p", text: "There is no single “export-ready” status for fresh fruit. Each importing country sets its own conditions per commodity and origin, and these change. We therefore confirm eligibility for each product–destination pair before a contract is signed." },
      { type: "h2", text: "Check the destination requirement first" },
      { type: "ul", items: ["United States: use the USDA APHIS ACIR database to look up the commodity and origin; treatment (e.g. irradiation) may be mandatory.", "European Union: plant health rules and maximum residue limits apply; some commodities face increased checks.", "Asian markets: several require registered growing-area and packhouse codes."] },
      { type: "h2", text: "Documents that usually accompany a shipment" },
      { type: "table", head: ["Document", "When"], rows: [["Commercial invoice & packing list", "Always"], ["Phytosanitary certificate", "Fresh plant products — per destination"], ["Certificate of origin", "When claiming tariff preference"], ["Treatment certificate", "When treatment is required"]] },
      { type: "note", text: "This guide is general information, not legal or regulatory advice. Importers remain responsible for verifying current requirements with the competent authority." },
    ],
  },
  {
    slug: "central-highlands-sourcing-profile",
    title: "Central Highlands sourcing profile: soils, smallholders and seasonality",
    pillar: "Origin insight",
    summary: "Why basalt soils and a sharp dry season shape Vietnam's robusta — and how smallholder supply is organised into traceable lots.",
    publishedAt: "2026-06-12",
    readingMinutes: 6,
    reviewedBy: "Sourcing team",
    relatedProducts: ["robusta-grade-1-screen-16", "black-pepper-550gl"],
    cta: { label: "Explore the Central Highlands origin", href: "/origins/central-highlands" },
    image: { kind: "origin", alt: "Red basalt soil and coffee rows", caption: "Landscape – basalt soils" },
    body: [
      { type: "p", text: "The Central Highlands plateau sits between 400 and 800 metres. Deep red basalt soils hold water well, and a dry season from November to April concentrates both harvest and flowering." },
      { type: "h2", text: "Who grows the coffee" },
      { type: "p", text: "Most farms are one to three hectares. Farmers sell dried cherry or green coffee to collectors and processors; organising them into registered farmer groups is what makes lot-level traceability possible." },
      { type: "h2", text: "What we record" },
      { type: "ul", items: ["Farmer group ID at every intake", "Plot geolocation where collected and approved", "Processing batch and export lot code"] },
    ],
  },
  {
    slug: "understanding-a-certificate-of-analysis",
    title: "Understanding a Certificate of Analysis (COA) for agricultural commodities",
    pillar: "Quality guide",
    summary: "What a COA should contain, how to check the lab's accreditation, and the difference between a sample COA and a lot COA.",
    publishedAt: "2026-05-20",
    readingMinutes: 5,
    reviewedBy: "QA laboratory",
    relatedProducts: ["cashew-kernels-w320", "black-pepper-550gl"],
    cta: { label: "Download a sample COA", href: "/api/documents/coa-sample-cashew" },
    image: { kind: "factory", alt: "Laboratory technician testing samples", caption: "Lab – moisture & aflatoxin testing" },
    body: [
      { type: "p", text: "A COA reports test results for a specific lot against a specification. A sample COA only shows the format — it is not evidence for any shipment." },
      { type: "h2", text: "What to check" },
      { type: "ul", items: ["Lot code matches the packing list and container marks.", "Test methods and units are stated.", "The laboratory is accredited (ISO/IEC 17025) for the listed tests.", "Results are compared to the contracted limits, not generic ones."] },
      { type: "h3", text: "Moisture vs water activity" },
      { type: "p", text: "Moisture is the percentage of water by weight. Water activity (aw) indicates how available that water is for microbial growth — often the better predictor of mould risk during sea freight." },
    ],
  },
  {
    slug: "eudr-timeline-update-coffee-buyers",
    title: "EUDR timeline update for coffee buyers",
    pillar: "Market update",
    summary: "Application dates, what operators must collect, and what information we can provide for in-scope coffee lots.",
    publishedAt: "2026-09-10",
    readingMinutes: 4,
    reviewedBy: "Compliance · Legal (pending)",
    relatedProducts: ["robusta-grade-1-screen-16", "arabica-cau-dat-washed"],
    cta: { label: "Request the EUDR information pack", href: "/contact?topic=eudr" },
    image: { kind: "origin", alt: "Mapped coffee plots", caption: "Origin – plot mapping" },
    body: [
      { type: "p", text: "Under the EU Deforestation Regulation (EUDR), coffee is an in-scope commodity. According to the European Commission, obligations apply to large and medium operators from 30 December 2026." },
      { type: "h2", text: "What operators need" },
      { type: "ul", items: ["Geolocation of the plots of land where the coffee was produced", "Evidence that production did not cause deforestation after 31 December 2020", "Evidence of compliance with relevant legislation of the country of production"] },
      { type: "h2", text: "What we can provide" },
      { type: "p", text: "For coffee lots sourced from mapped farmer groups we can share due-diligence information approved by our legal and operations teams. We do not describe any product as “EUDR compliant” — compliance is the operator's determination." },
      { type: "note", text: "Regulatory updates must be reviewed by compliance before publishing. Check the European Commission's EUDR page for the current official dates." },
    ],
  },
];
