import type { MediaAsset, Packing, Product } from "./types";

/*
 * Product catalogue — ILLUSTRATIVE values only (§9.2: "Value (illustrative only)").
 * `null` spec values render as "Pending verification" so missing data is
 * visible instead of invented.
 */

const img = (src: string, alt: string, motif: MediaAsset["motif"], focal = "50% 50%"): MediaAsset => ({ src, alt, kind: "product", motif, focal });

const jute60: Packing = {
  id: "jute-60",
  name: "Jute bag",
  netWeight: "60 kg",
  material: "New jute, GrainPro liner optional",
  loading: "≈ 19.2 MT / 20 ft (320 bags)",
};
const bulkLiner: Packing = {
  id: "bulk-liner",
  name: "Bulk container liner",
  netWeight: "≈ 21 MT",
  material: "Food-grade PE liner",
  loading: "≈ 21 MT / 20 ft",
};
const bigBag: Packing = {
  id: "big-bag",
  name: "Big bag (FIBC)",
  netWeight: "1,000 kg",
  material: "Woven PP with inner liner",
  loading: "≈ 20 MT / 20 ft",
};
const cashewTin: Packing = {
  id: "tin-2268",
  name: "Vacuum tin, 2 per carton",
  netWeight: "2 × 11.34 kg (50 lb)",
  material: "Tinplate, CO₂ flushed",
  loading: "≈ 700 cartons / 20 ft",
};
const cashewBag: Packing = {
  id: "bag-2268",
  name: "Vacuum bag, 2 per carton",
  netWeight: "2 × 11.34 kg (50 lb)",
  material: "PA/PE laminated, CO₂ flushed",
  loading: "≈ 700 cartons / 20 ft",
};
const cashewRetail: Packing = {
  id: "retail-pouch",
  name: "Retail pouch",
  netWeight: "200 g – 1 kg",
  material: "Stand-up zip pouch",
  privateLabel: true,
};
const pepperBag: Packing = { id: "pp-25-pepper", name: "PP bag", netWeight: "25 / 50 kg", material: "PP with PE inner", loading: "≈ 16–18 MT / 20 ft" };
const spiceCarton: Packing = { id: "carton-spice", name: "Carton", netWeight: "10 – 15 kg", material: "Corrugated with PE liner", loading: "≈ 12–16 MT / 40 ft" };
const spiceBag: Packing = { id: "pp-spice", name: "PP bag", netWeight: "20 – 25 kg", material: "PP with PE inner", loading: "≈ 12–14 MT / 40 ft" };
const powderBag: Packing = { id: "kraft-powder", name: "Kraft paper bag", netWeight: "25 kg", material: "Multi-wall kraft with PE inner", loading: "≈ 14 MT / 20 ft" };
const mangoCarton: Packing = {
  id: "carton-mango",
  name: "Bulk carton",
  netWeight: "10 kg (2 × 5 kg PE bags)",
  material: "Food-grade PE inner + master carton",
  loading: "≈ 8–10 MT / 20 ft",
};
const mangoPouch: Packing = {
  id: "pouch-owi-chewi",
  name: "Owi Chewi retail pouch",
  netWeight: "100 g / 250 g / 500 g",
  material: "Stand-up zip pouch, nitrogen flushed",
  loading: "≈ 1,200 cartons / 20 ft",
  privateLabel: true,
};

const coffeePorts = ["Cat Lai (Ho Chi Minh City)", "Cai Mep"];
const southPorts = ["Cat Lai (Ho Chi Minh City)", "Cai Mep"];
const northPorts = ["Hai Phong", "Cat Lai (Ho Chi Minh City)"];
const standardTerms = ["FOB", "CFR", "CIF"];

export const products: Product[] = [
  // ------------------------------------------------------------------ COFFEE
  {
    slug: "robusta-grade-1-screen-16",
    category: "coffee",
    name: "Robusta Grade 1 – Screen 16",
    shortDescription: "Clean, wet-polished robusta for roasters and soluble plants that need a consistent S16 base.",
    overview:
      "Our core export robusta: natural-processed cherry from Dak Lak and Gia Lai farmer groups, cleaned, screen-graded to 16 and colour-sorted. Available cleaned or wet-polished. Offered by crop and lot; the pre-shipment sample is approved against your type sample.",
    originIds: ["central-highlands"],
    crop: "2026/27",
    processing: ["Natural (dry)", "Cleaned", "Wet polished"],
    grade: "Grade 1",
    spec: {
      species: "Coffea canephora (Robusta)",
      grade: "Grade 1",
      screen: "16+ (min. 90% on S16)",
      moistureMax: 12.5,
      foreignMatterMax: 0.1,
      blackBrokenMax: 2,
      processing: "Cleaned / wet polished",
      cropYear: "2026/27",
      packing: "60 kg jute · bulk liner",
      shelfLife: null,
    },
    facets: { grade: "Grade 1", certifications: ["HACCP", "Rainforest Alliance"], packaging: ["Jute bag", "Bulk liner"] },
    packings: [jute60, bulkLiner, bigBag],
    seasonality: [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2],
    certificateIds: ["haccp-daklak", "ra-coffee-group"],
    documentIds: ["spec-robusta-grade-1-screen-16", "coa-sample-coffee", "cert-haccp-daklak"],
    facilityId: "dak-lak-coffee-plant",
    loadingPorts: coffeePorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    rfqGrades: ["Grade 1 · Screen 16 · cleaned", "Grade 1 · Screen 16 · wet polished", "Grade 1 · Screen 16 · RA certified"],
    featured: true,
    image: img("/images/coffee/beans-2.jpg", "Coffee beans filling the frame", "bean"),
    gallery: [
      img("/images/coffee/cherries-branch.jpg", "Ripe and unripe robusta cherries on the branch", "cherry"),
      img("/images/coffee/beans-scoop.jpg", "Coffee beans in a scoop and jute sack", "bean", "80% 50%"),
    ],
    verified: false,
  },
  {
    slug: "robusta-grade-1-screen-18",
    category: "coffee",
    name: "Robusta Grade 1 – Screen 18",
    shortDescription: "Large-bean wet-polished robusta for espresso blends and premium roasters.",
    overview:
      "Top screen robusta selected from the same Central Highlands supply chain as our S16. Wet-polished for appearance and colour-sorted twice to keep black and broken beans low.",
    originIds: ["central-highlands"],
    crop: "2026/27",
    processing: ["Natural (dry)", "Wet polished", "Double sorted"],
    grade: "Grade 1",
    spec: {
      species: "Coffea canephora (Robusta)",
      grade: "Grade 1",
      screen: "18+ (min. 90% on S18)",
      moistureMax: 12.5,
      foreignMatterMax: 0.1,
      blackBrokenMax: 1,
      processing: "Wet polished, double sorted",
      cropYear: "2026/27",
      packing: "60 kg jute",
      shelfLife: null,
    },
    facets: { grade: "Grade 1", certifications: ["HACCP"], packaging: ["Jute bag"] },
    packings: [jute60, bulkLiner],
    seasonality: [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2],
    certificateIds: ["haccp-daklak"],
    documentIds: ["spec-robusta-grade-1-screen-18", "coa-sample-coffee"],
    facilityId: "dak-lak-coffee-plant",
    loadingPorts: coffeePorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    image: img("/images/coffee/beans-closeup.jpg", "Large coffee beans, close-up", "bean"),
    gallery: [img("/images/coffee/beans-1.jpg", "Coffee beans, overhead", "bean")],
    verified: false,
  },
  {
    slug: "robusta-grade-2-screen-13",
    category: "coffee",
    name: "Robusta Grade 2 – Screen 13",
    shortDescription: "Cost-efficient robusta for soluble coffee and blend fillers.",
    overview:
      "Standard Grade 2 robusta with higher defect tolerance, suited to instant coffee extraction and value blends. Offered FAQ-style or to buyer specification.",
    originIds: ["central-highlands"],
    crop: "2026/27",
    processing: ["Natural (dry)", "Cleaned"],
    grade: "Grade 2",
    spec: {
      species: "Coffea canephora (Robusta)",
      grade: "Grade 2",
      screen: "13+ (min. 90% on S13)",
      moistureMax: 13,
      foreignMatterMax: 0.5,
      blackBrokenMax: 5,
      processing: "Cleaned",
      cropYear: "2026/27",
      packing: "60 kg jute · bulk liner",
      shelfLife: null,
    },
    facets: { grade: "Grade 2", certifications: ["HACCP"], packaging: ["Jute bag", "Bulk liner"] },
    packings: [jute60, bulkLiner],
    seasonality: [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2],
    certificateIds: ["haccp-daklak"],
    documentIds: ["spec-robusta-grade-2-screen-13", "coa-sample-coffee"],
    facilityId: "dak-lak-coffee-plant",
    loadingPorts: coffeePorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    image: img("/images/coffee/beans-1.jpg", "Coffee beans, overhead", "bean"),
    gallery: [],
    verified: false,
  },
  {
    slug: "arabica-cau-dat-washed",
    category: "coffee",
    name: "Arabica Cau Dat – Washed",
    shortDescription: "Washed Catimor Arabica from 1,500 m, selected by cup for specialty roasters.",
    overview:
      "Fully washed Arabica from farm clusters on the Cau Dat plateau, dried on raised beds and hulled to order. Lots are cupped and offered with a cupping score range — final score confirmed on pre-shipment sample.",
    originIds: ["lam-dong"],
    crop: "2026/27",
    processing: ["Washed", "Raised-bed dried"],
    grade: "Specialty",
    spec: {
      species: "Coffea arabica (Catimor)",
      grade: "Specialty / Premium",
      screen: "16+",
      moistureMax: 11.5,
      foreignMatterMax: 0,
      blackBrokenMax: 0.5,
      processing: "Fully washed",
      cropYear: "2026/27",
      packing: "60 kg jute + GrainPro",
      shelfLife: null,
    },
    facets: { grade: "Specialty", certifications: [], packaging: ["Jute bag"] },
    packings: [jute60],
    seasonality: [2, 1, 1, 1, 1, 1, 0, 0, 0, 2, 2, 2],
    certificateIds: [],
    documentIds: ["spec-arabica-cau-dat-washed", "coa-sample-coffee"],
    loadingPorts: coffeePorts,
    incoterms: ["FOB", "CIF", "DAP"],
    moq: "From 1 pallet (LCL) · 20 ft preferred",
    rfqGrades: ["Washed · 84+ cup", "Washed · 82–84 cup", "Honey process", "Natural process"],
    featured: true,
    image: img("/images/coffee/cherries-tree.jpg", "Coffee cherries ripening on the tree", "cherry", "50% 40%"),
    gallery: [img("/images/coffee/cherries-dark.jpg", "Coffee branch with ripe cherries", "cherry")],
    verified: false,
  },
  {
    slug: "fine-robusta-honey",
    category: "coffee",
    name: "Fine Robusta – Honey Processed",
    shortDescription: "Red-cherry selected robusta, honey processed for cup-driven blends.",
    overview:
      "Hand-picked ripe cherry, pulped and dried with mucilage on raised beds. A cleaner, sweeter robusta profile for specialty blends and single-origin espresso.",
    originIds: ["central-highlands", "lam-dong"],
    crop: "2026/27",
    processing: ["Honey", "Raised-bed dried"],
    grade: "Fine Robusta",
    spec: {
      species: "Coffea canephora (Robusta)",
      grade: "Fine Robusta",
      screen: "16+",
      moistureMax: 12,
      foreignMatterMax: 0,
      blackBrokenMax: 0.5,
      processing: "Honey",
      cropYear: "2026/27",
      packing: "60 kg jute + GrainPro",
      shelfLife: null,
    },
    facets: { grade: "Specialty", certifications: [], packaging: ["Jute bag"] },
    packings: [jute60],
    seasonality: [2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2],
    certificateIds: [],
    documentIds: ["spec-fine-robusta-honey"],
    loadingPorts: coffeePorts,
    incoterms: ["FOB", "CIF", "DAP"],
    moq: "From 1 pallet (LCL)",
    image: img("/images/coffee/cherries-cluster.jpg", "Cluster of red and green coffee cherries", "cherry"),
    gallery: [],
    verified: false,
  },

  // ------------------------------------------------------------------ CASHEW
  {
    slug: "cashew-kernels-w320",
    category: "cashew",
    name: "Cashew Kernels W320",
    shortDescription: "The most traded white whole grade — for snack packers and retailers.",
    overview:
      "White whole kernels, 300–320 per pound, graded to AFI reference and vacuum-packed in tins or bags. RCN origin is declared on every lot.",
    originIds: ["southeast-cashew-belt"],
    crop: "2026 processing",
    processing: ["Steamed & shelled", "Peeled", "Graded", "Vacuum packed"],
    grade: "W320",
    spec: {
      grade: "W320 (white wholes)",
      count: "300 – 320 kernels / lb",
      moistureMax: 5,
      brokenMax: 5,
      color: "White / pale ivory",
      standard: "AFI specification (reference)",
      packing: "Vacuum tin or bag, 2 × 11.34 kg",
      shelfLife: "12 months (vacuum)",
    },
    facets: { grade: "W320", certifications: ["BRCGS", "ISO 22000", "Kosher"], packaging: ["Vacuum tin", "Vacuum bag", "Retail / private label"] },
    packings: [cashewTin, cashewBag, cashewRetail],
    seasonality: [1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    certificateIds: ["brcgs-cashew", "iso22000-cashew", "kosher-cashew"],
    documentIds: ["spec-cashew-kernels-w320", "coa-sample-cashew", "cert-brcgs-cashew"],
    facilityId: "binh-phuoc-cashew-plant",
    loadingPorts: southPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container (≈ 700 cartons)",
    featured: true,
    image: img("/images/cashew/basket.jpg", "White cashew kernels in a woven basket", "kernel"),
    gallery: [
      img("/images/cashew/sack.jpg", "Cashew kernels spilling from a jute sack", "kernel"),
      img("/images/cashew/bowl-white.jpg", "Cashew kernels in a white bowl", "kernel"),
    ],
    verified: false,
  },
  {
    slug: "cashew-kernels-w240",
    category: "cashew",
    name: "Cashew Kernels W240",
    shortDescription: "Large white wholes for premium retail and gifting.",
    overview:
      "Larger-count white wholes (220–240 per pound) selected for premium snack and gifting ranges. Same processing and packing controls as W320.",
    originIds: ["southeast-cashew-belt"],
    crop: "2026 processing",
    processing: ["Steamed & shelled", "Peeled", "Graded", "Vacuum packed"],
    grade: "W240",
    spec: {
      grade: "W240 (white wholes)",
      count: "220 – 240 kernels / lb",
      moistureMax: 5,
      brokenMax: 5,
      color: "White / pale ivory",
      standard: "AFI specification (reference)",
      packing: "Vacuum tin or bag, 2 × 11.34 kg",
      shelfLife: "12 months (vacuum)",
    },
    facets: { grade: "W240", certifications: ["BRCGS", "ISO 22000", "Kosher"], packaging: ["Vacuum tin", "Vacuum bag"] },
    packings: [cashewTin, cashewBag],
    seasonality: [1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    certificateIds: ["brcgs-cashew", "iso22000-cashew", "kosher-cashew"],
    documentIds: ["spec-cashew-kernels-w240", "coa-sample-cashew"],
    facilityId: "binh-phuoc-cashew-plant",
    loadingPorts: southPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    image: img("/images/cashew/bowl-white.jpg", "Large white cashew kernels in a bowl", "kernel"),
    gallery: [],
    verified: false,
  },
  {
    slug: "cashew-splits-ws",
    category: "cashew",
    name: "Cashew Splits WS",
    shortDescription: "White splits for bakery, confectionery and ingredient use.",
    overview:
      "Naturally split white kernels — the cost-efficient choice when whole-kernel appearance isn't required. Popular with bakery, cereal and confectionery manufacturers.",
    originIds: ["southeast-cashew-belt"],
    crop: "2026 processing",
    processing: ["Steamed & shelled", "Peeled", "Graded", "Vacuum packed"],
    grade: "WS",
    spec: {
      grade: "WS (white splits)",
      count: "—",
      moistureMax: 5,
      brokenMax: 5,
      color: "White / pale ivory",
      standard: "AFI specification (reference)",
      packing: "Vacuum bag, 2 × 11.34 kg",
      shelfLife: "12 months (vacuum)",
    },
    facets: { grade: "WS / Pieces", certifications: ["BRCGS", "ISO 22000"], packaging: ["Vacuum bag"] },
    packings: [cashewBag],
    seasonality: [1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    certificateIds: ["brcgs-cashew", "iso22000-cashew"],
    documentIds: ["spec-cashew-splits-ws"],
    facilityId: "binh-phuoc-cashew-plant",
    loadingPorts: southPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    image: img("/images/cashew/roasted-bowls.jpg", "Cashew kernels in wooden bowls", "kernel"),
    gallery: [],
    verified: false,
  },

  // ------------------------------------------------------------------ PEPPER
  {
    slug: "black-pepper-550gl",
    category: "pepper",
    name: "Black Pepper 550 g/l – Cleaned",
    shortDescription: "Machine-cleaned black pepper for grinders and spice packers.",
    overview:
      "Black pepper from Gia Lai and Dak Lak, machine-cleaned and graded to 550 g/l bulk density. Steam sterilisation available on request for buyers with microbiological limits.",
    originIds: ["central-highlands", "southeast-cashew-belt"],
    crop: "2026",
    processing: ["Sun-dried", "Machine cleaned", "Steam sterilised (option)"],
    grade: "550 g/l",
    spec: {
      type: "Black pepper, whole",
      density: 550,
      moistureMax: 13,
      extraneousMax: 0.5,
      lightBerriesMax: 2,
      processing: "Machine cleaned",
      micro: "Per buyer spec (sterilised option)",
      packing: "25 / 50 kg PP",
    },
    facets: { grade: "550 g/l", certifications: ["HACCP", "Halal"], packaging: ["PP bag"] },
    packings: [pepperBag, bigBag],
    seasonality: [1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    certificateIds: ["haccp-daklak", "halal-daklak"],
    documentIds: ["spec-black-pepper-550gl", "coa-sample-pepper"],
    facilityId: "dak-lak-coffee-plant",
    loadingPorts: southPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    featured: true,
    image: img("/images/pepper/spoon-sack.jpg", "Black peppercorns in a spoon beside a jute sack", "peppercorn", "55% 55%"),
    gallery: [
      img("/images/pepper/green-clusters.jpg", "Green pepper berries on the vine", "peppercorn"),
      img("/images/pepper/hands.jpg", "Hands holding dried black peppercorns", "peppercorn"),
    ],
    verified: false,
  },
  {
    slug: "white-pepper-630gl",
    category: "pepper",
    name: "White Pepper 630 g/l",
    shortDescription: "Double-washed white pepper for sauces, seasoning and retail.",
    overview:
      "Retted and double-washed white pepper with a clean, pale surface. Graded to 630 g/l and dried to low moisture for stable ocean freight.",
    originIds: ["central-highlands"],
    crop: "2026",
    processing: ["Retted", "Double washed", "Sun-dried"],
    grade: "630 g/l",
    spec: {
      type: "White pepper, whole",
      density: 630,
      moistureMax: 13,
      extraneousMax: 0.2,
      lightBerriesMax: null,
      processing: "Double washed",
      micro: "Per buyer spec",
      packing: "25 / 50 kg PP",
    },
    facets: { grade: "630 g/l", certifications: ["HACCP"], packaging: ["PP bag"] },
    packings: [pepperBag],
    seasonality: [1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    certificateIds: ["haccp-daklak"],
    documentIds: ["spec-white-pepper-630gl"],
    facilityId: "dak-lak-coffee-plant",
    loadingPorts: southPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    image: img("/images/pepper/spoon-dark.jpg", "Peppercorns in a metal spoon on a dark surface", "peppercorn"),
    gallery: [],
    verified: false,
  },

  // ------------------------------------------------------------------ CINNAMON
  {
    slug: "split-cassia-cinnamon",
    category: "cinnamon",
    name: "Split Cassia Cinnamon",
    shortDescription: "Scraped split cassia bark with high volatile oil for grinders.",
    overview:
      "Cassia bark from 10–15-year-old trees in Yen Bai, scraped and split, sun-dried and re-dried before packing. Specified by length, oil content and moisture.",
    originIds: ["northern-mountains"],
    crop: "Spring 2026",
    processing: ["Scraped", "Sun-dried", "Re-dried"],
    grade: "Split 2–3% oil",
    spec: {
      form: "Split, scraped",
      size: "30 – 45 cm, width 2 – 4 cm",
      moistureMax: 13.5,
      oilContent: 3,
      admixtureMax: 1,
      processing: "Sun-dried, scraped",
      packing: "10 kg carton / PP bag",
      shelfLife: "24 months",
    },
    facets: { grade: "Split", certifications: [], packaging: ["Carton", "PP bag"] },
    packings: [spiceCarton, spiceBag],
    seasonality: [1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 1],
    certificateIds: [],
    documentIds: ["spec-split-cassia-cinnamon", "coa-sample-spices"],
    loadingPorts: northPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    featured: true,
    image: img("/images/cinnamon/sticks-pile.jpg", "Pile of cassia cinnamon bark", "stick"),
    gallery: [
      img("/images/cinnamon/stack.jpg", "Stacked cassia cinnamon sticks", "stick"),
      img("/images/mixed/anise-cinnamon-sticks.jpg", "Cassia sticks and star anise on wood", "stick", "30% 50%"),
    ],
    verified: false,
  },
  {
    slug: "cassia-sticks-8cm",
    category: "cinnamon",
    name: "Cassia Sticks – 8 cm Cut",
    shortDescription: "Rolled cassia sticks cut to 8 cm for retail jars and food service.",
    overview:
      "Thin-bark tube cassia rolled and cut to a uniform 8 cm length, cleaned and sorted by diameter. Suitable for retail spice jars, mulled drinks and food service.",
    originIds: ["northern-mountains"],
    crop: "Spring 2026",
    processing: ["Rolled", "Cut to length", "Sun-dried"],
    grade: "Stick 8 cm",
    spec: {
      form: "Tube / stick",
      size: "8 cm (±0.5 cm), Ø 0.8 – 1.2 cm",
      moistureMax: 13,
      oilContent: 2.5,
      admixtureMax: 0.5,
      processing: "Rolled, cut, sun-dried",
      packing: "10 kg carton",
      shelfLife: "24 months",
    },
    facets: { grade: "Stick / tube", certifications: [], packaging: ["Carton", "Retail / private label"] },
    packings: [spiceCarton],
    seasonality: [1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 1],
    certificateIds: [],
    documentIds: ["spec-cassia-sticks-8cm"],
    loadingPorts: northPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container · mixed load with star anise possible",
    image: img("/images/cinnamon/rolls-powder.jpg", "Rolled cassia sticks with cinnamon powder", "stick"),
    gallery: [],
    verified: false,
  },
  {
    slug: "cassia-powder",
    category: "cinnamon",
    name: "Cassia Cinnamon Powder",
    shortDescription: "Finely ground cassia for bakery, seasoning blends and retail.",
    overview:
      "Cassia bark cleaned, re-dried and milled to buyer mesh size. Steam sterilisation available for buyers with microbiological limits.",
    originIds: ["northern-mountains"],
    crop: "2026",
    processing: ["Milled", "Sieved", "Steam sterilised (option)"],
    grade: "Powder 60 mesh",
    spec: {
      form: "Powder",
      size: "60 mesh (other mesh on request)",
      moistureMax: 12,
      oilContent: 2,
      admixtureMax: null,
      processing: "Milled, sieved",
      packing: "25 kg kraft bag",
      shelfLife: "18 months",
    },
    facets: { grade: "Powder", certifications: [], packaging: ["Kraft bag"] },
    packings: [powderBag],
    seasonality: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    certificateIds: [],
    documentIds: ["spec-cassia-powder"],
    loadingPorts: northPorts,
    incoterms: standardTerms,
    moq: "5 MT",
    image: img("/images/cinnamon/powder-sticks.jpg", "Cassia sticks resting on cinnamon powder", "stick"),
    gallery: [],
    verified: false,
  },

  // ------------------------------------------------------------------ STAR ANISE
  {
    slug: "star-anise-autumn",
    category: "anise",
    name: "Star Anise – Autumn Crop",
    shortDescription: "Whole, reddish-brown star anise from Lang Son's main crop.",
    overview:
      "Autumn-crop star anise from Lang Son: larger, fuller stars with rich aroma. Graded by proportion of whole stars and dried to safe moisture.",
    originIds: ["northern-mountains"],
    crop: "Autumn 2026",
    processing: ["Sun-dried", "Hand graded"],
    grade: "Autumn ≥ 80% whole",
    spec: {
      form: "Whole stars",
      size: "≥ 2.5 cm, ≥ 80% whole",
      moistureMax: 13,
      oilContent: null,
      admixtureMax: 1,
      processing: "Sun-dried, hand graded",
      packing: "10 kg carton",
      shelfLife: "24 months",
    },
    facets: { grade: "Autumn crop", certifications: [], packaging: ["Carton"] },
    packings: [spiceCarton],
    seasonality: [1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1],
    certificateIds: [],
    documentIds: ["spec-star-anise-autumn", "coa-sample-spices"],
    loadingPorts: northPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    featured: true,
    image: img("/images/anise/pile.jpg", "Whole star anise piled on a wooden table", "star"),
    gallery: [
      img("/images/anise/top-view.jpg", "Whole star anise, top view", "star"),
      img("/images/anise/single.jpg", "Single star anise on a dark background", "star"),
    ],
    verified: false,
  },
  {
    slug: "star-anise-spring",
    category: "anise",
    name: "Star Anise – Spring Crop",
    shortDescription: "Smaller, paler spring-crop stars — cost-efficient for grinding and extraction.",
    overview:
      "Spring-crop star anise with smaller stars and a higher share of broken pieces. Well suited to grinding, oil extraction and seasoning blends.",
    originIds: ["northern-mountains"],
    crop: "Spring 2026",
    processing: ["Sun-dried", "Machine sorted"],
    grade: "Spring ≥ 70% whole",
    spec: {
      form: "Whole stars / broken",
      size: "≥ 2 cm, ≥ 70% whole",
      moistureMax: 13,
      oilContent: null,
      admixtureMax: 1.5,
      processing: "Sun-dried, machine sorted",
      packing: "20 kg PP bag / 10 kg carton",
      shelfLife: "24 months",
    },
    facets: { grade: "Spring crop", certifications: [], packaging: ["Carton", "PP bag"] },
    packings: [spiceBag, spiceCarton],
    seasonality: [1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1],
    certificateIds: [],
    documentIds: ["spec-star-anise-spring"],
    loadingPorts: northPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    image: img("/images/anise/dark-pattern.jpg", "Star anise arranged on a dark surface", "star"),
    gallery: [],
    verified: false,
  },

  // ------------------------------------------------------------------ DRIED MANGO
  {
    slug: "soft-dried-mango-bulk",
    category: "mango",
    name: "Soft Dried Mango – Bulk Slices",
    shortDescription: "Chewy dried mango slices in bulk cartons for snack packers and food service.",
    overview:
      "Ripe Mekong Delta mangoes are peeled, sliced and gently dried to a soft, chewy texture. Packed in food-grade bags inside 10 kg cartons for repacking, trail mixes and food service.",
    originIds: ["mekong-delta"],
    crop: "2026 season",
    processing: ["Sliced", "Low-temperature dried", "Metal detected"],
    grade: "Slices",
    spec: {
      variety: "Cat Chu / Keo (per availability)",
      cut: "Slices 5 – 8 mm, 6 – 10 cm",
      moistureMax: 18,
      waterActivityMax: 0.65,
      sugar: "Cane sugar infused (per spec)",
      additives: "Citric acid; no artificial colour",
      texture: "Soft, chewy",
      packing: "10 kg carton (2 × 5 kg PE)",
      shelfLife: "12 months",
    },
    facets: { grade: "Slices", certifications: ["HACCP"], packaging: ["Carton"] },
    packings: [mangoCarton],
    seasonality: [1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1],
    certificateIds: ["haccp-dongthap"],
    documentIds: ["spec-soft-dried-mango-bulk", "coa-sample-mango"],
    facilityId: "dong-thap-fruit-plant",
    loadingPorts: southPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container · mixed pallets possible",
    featured: true,
    image: img("/images/mango/paper.jpg", "Soft dried mango slices on baking paper", "fruit"),
    gallery: [
      img("/images/mango/closeup.jpg", "Dried mango pieces, close-up", "fruit"),
      img("/images/mango/slices-white.jpg", "Dried mango slices on a white background", "fruit"),
    ],
    verified: false,
  },
  {
    slug: "owi-chewi-dried-mango",
    category: "mango",
    name: "Owi Chewi Soft Dried Mango – Retail Pouch",
    shortDescription: "Our own Owi Chewi brand: ready-to-shelf pouches of chewy dried mango.",
    overview:
      "Owi Chewi is our retail brand of soft dried mango, packed in resealable stand-up pouches. Available for distributors and retailers as branded stock, or as private label using the same product.",
    originIds: ["mekong-delta"],
    crop: "2026 season",
    processing: ["Sliced", "Low-temperature dried", "Nitrogen-flushed pouch"],
    grade: "Retail pouch",
    spec: {
      variety: "Cat Chu / Keo (per availability)",
      cut: "Slices",
      moistureMax: 18,
      waterActivityMax: 0.65,
      sugar: "Lightly sweetened",
      additives: "Citric acid; no artificial colour",
      texture: "Soft, chewy",
      packing: "100 g / 250 g / 500 g pouch",
      shelfLife: "12 months",
    },
    facets: { grade: "Retail pouch", certifications: ["HACCP"], packaging: ["Retail / private label"] },
    packings: [mangoPouch, mangoCarton],
    seasonality: [1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1],
    certificateIds: ["haccp-dongthap"],
    documentIds: ["spec-owi-chewi-dried-mango"],
    facilityId: "dong-thap-fruit-plant",
    loadingPorts: southPorts,
    incoterms: ["FOB", "CFR", "CIF", "DAP"],
    moq: "200 cartons · mixed pouch sizes",
    image: img("/images/mango/bowl-1.jpg", "Owi Chewi soft dried mango in a bowl", "fruit", "50% 55%"),
    gallery: [img("/images/mango/bowl-2.jpg", "Bowl of soft dried mango slices", "fruit")],
    verified: false,
  },
  {
    slug: "low-sugar-dried-mango",
    category: "mango",
    name: "Low-Sugar Dried Mango",
    shortDescription: "Reduced-sugar dried mango for health-focused snack ranges.",
    overview:
      "Dried mango with no added sucrose beyond a light infusion, keeping the fruit's natural sweetness. Popular with health-food retailers and breakfast-cereal manufacturers.",
    originIds: ["mekong-delta"],
    crop: "2026 season",
    processing: ["Sliced", "Low-temperature dried"],
    grade: "Low-sugar",
    spec: {
      variety: "Cat Chu / Keo (per availability)",
      cut: "Slices or 10 × 10 mm dices",
      moistureMax: 16,
      waterActivityMax: 0.6,
      sugar: "Reduced (per spec)",
      additives: "None",
      texture: "Soft, slightly firm",
      packing: "10 kg carton",
      shelfLife: "9 months",
    },
    facets: { grade: "Low-sugar", certifications: ["HACCP"], packaging: ["Carton"] },
    packings: [mangoCarton],
    seasonality: [1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1],
    certificateIds: ["haccp-dongthap"],
    documentIds: ["spec-low-sugar-dried-mango"],
    facilityId: "dong-thap-fruit-plant",
    loadingPorts: southPorts,
    incoterms: standardTerms,
    moq: "3 MT",
    image: img("/images/mango/slices-white-2.jpg", "Dried mango slices on a white background", "fruit"),
    gallery: [],
    verified: false,
  },
];
