import type { Packing, Product } from "./types";

/*
 * Product catalogue — ILLUSTRATIVE values only (§9.2: "Value (illustrative only)").
 * `null` spec values render as "Pending verification" so missing data is
 * visible instead of invented.
 */

const jute60: Packing = {
  id: "jute-60",
  name: "Jute bag",
  netWeight: "60 kg",
  material: "New jute, GrainPro liner optional",
  loading: "≈ 19.2 MT / 20 ft (320 bags)",
};
const bulkLiner: Packing = {
  id: "bulk-liner",
  name: "Bulk container liner",
  netWeight: "≈ 21 MT",
  material: "Food-grade PE liner",
  loading: "≈ 21 MT / 20 ft",
};
const bigBag: Packing = {
  id: "big-bag",
  name: "Big bag (FIBC)",
  netWeight: "1,000 kg",
  material: "Woven PP with inner liner",
  loading: "≈ 20 MT / 20 ft",
};
const pp25: Packing = { id: "pp-25", name: "PP woven bag", netWeight: "25 kg", material: "PP with PE inner", loading: "≈ 25 MT / 20 ft" };
const pp50: Packing = { id: "pp-50", name: "PP woven bag", netWeight: "50 kg", material: "PP with PE inner", loading: "≈ 25 MT / 20 ft" };
const retailRice: Packing = {
  id: "retail-1-5",
  name: "Retail bag",
  netWeight: "1 / 2 / 5 kg",
  material: "PA/PE vacuum or printed laminate",
  loading: "≈ 22 MT / 20 ft",
  privateLabel: true,
};
const cashewTin: Packing = {
  id: "tin-2268",
  name: "Vacuum tin, 2 per carton",
  netWeight: "2 × 11.34 kg (50 lb)",
  material: "Tinplate, CO₂ flushed",
  loading: "≈ 700 cartons / 20 ft",
};
const cashewBag: Packing = {
  id: "bag-2268",
  name: "Vacuum bag, 2 per carton",
  netWeight: "2 × 11.34 kg (50 lb)",
  material: "PA/PE laminated, CO₂ flushed",
  loading: "≈ 700 cartons / 20 ft",
};
const cashewRetail: Packing = {
  id: "retail-pouch",
  name: "Retail pouch",
  netWeight: "200 g – 1 kg",
  material: "Stand-up zip pouch",
  privateLabel: true,
};
const pepperBag: Packing = { id: "pp-25-pepper", name: "PP bag", netWeight: "25 / 50 kg", material: "PP with PE inner", loading: "≈ 16–18 MT / 20 ft" };
const fruitCarton: Packing = {
  id: "carton-fruit",
  name: "Ventilated carton",
  netWeight: "5 – 10 kg",
  material: "Corrugated, foam net per fruit",
  loading: "≈ 20 pallets / 40 ft reefer",
};
const frozenCarton: Packing = {
  id: "carton-frozen",
  name: "Frozen carton",
  netWeight: "10 kg (vacuum inner)",
  material: "PE inner + master carton",
  loading: "≈ 24 MT / 40 ft reefer",
};
const spiceCarton: Packing = { id: "carton-spice", name: "Carton", netWeight: "10 – 15 kg", material: "Corrugated with PE liner", loading: "≈ 12–16 MT / 40 ft" };

const coffeePorts = ["Cat Lai (Ho Chi Minh City)", "Cai Mep"];
const southPorts = ["Cat Lai (Ho Chi Minh City)", "Cai Mep"];
const northPorts = ["Hai Phong"];
const standardTerms = ["FOB", "CFR", "CIF"];

export const products: Product[] = [
  // ------------------------------------------------------------------ COFFEE
  {
    slug: "robusta-grade-1-screen-16",
    category: "coffee",
    name: "Robusta Grade 1 – Screen 16",
    shortDescription: "Clean, wet-polished robusta for roasters and soluble plants that need a consistent S16 base.",
    overview:
      "Our core export robusta: natural-processed cherry from Dak Lak and Gia Lai farmer groups, cleaned, screen-graded to 16 and colour-sorted. Available cleaned or wet-polished. Offered by crop and lot; the pre-shipment sample is approved against your type sample.",
    originIds: ["central-highlands"],
    crop: "2026/27",
    processing: ["Natural (dry)", "Cleaned", "Wet polished"],
    grade: "Grade 1",
    spec: {
      species: "Coffea canephora (Robusta)",
      grade: "Grade 1",
      screen: "16+ (min. 90% on S16)",
      moistureMax: 12.5,
      foreignMatterMax: 0.1,
      blackBrokenMax: 2,
      processing: "Cleaned / wet polished",
      cropYear: "2026/27",
      packing: "60 kg jute · bulk liner",
      shelfLife: null,
    },
    facets: { grade: "Grade 1", certifications: ["HACCP", "Rainforest Alliance"], packaging: ["Jute bag", "Bulk liner"] },
    packings: [jute60, bulkLiner, bigBag],
    seasonality: [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2],
    certificateIds: ["haccp-daklak", "ra-coffee-group"],
    documentIds: ["spec-robusta-grade-1-screen-16", "coa-sample-coffee", "cert-haccp-daklak"],
    facilityId: "dak-lak-coffee-plant",
    loadingPorts: coffeePorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    rfqGrades: ["Grade 1 · Screen 16 · cleaned", "Grade 1 · Screen 16 · wet polished", "Grade 1 · Screen 16 · RA certified"],
    featured: true,
    image: { kind: "product", motif: "bean", alt: "Robusta Grade 1 Screen 16 green coffee beans", caption: "Product macro – Robusta S16" },
    gallery: [
      { kind: "product", motif: "bean", alt: "Robusta screen 16 beans on sieve", caption: "Macro – screen check" },
      { kind: "logistics", alt: "Jute bags stacked for loading", caption: "Packing – 60 kg jute" },
    ],
    verified: false,
  },
  {
    slug: "robusta-grade-1-screen-18",
    category: "coffee",
    name: "Robusta Grade 1 – Screen 18",
    shortDescription: "Large-bean wet-polished robusta for espresso blends and premium roasters.",
    overview:
      "Top screen robusta selected from the same Central Highlands supply chain as our S16. Wet-polished for appearance and colour-sorted twice to keep black and broken beans low.",
    originIds: ["central-highlands"],
    crop: "2026/27",
    processing: ["Natural (dry)", "Wet polished", "Double sorted"],
    grade: "Grade 1",
    spec: {
      species: "Coffea canephora (Robusta)",
      grade: "Grade 1",
      screen: "18+ (min. 90% on S18)",
      moistureMax: 12.5,
      foreignMatterMax: 0.1,
      blackBrokenMax: 1,
      processing: "Wet polished, double sorted",
      cropYear: "2026/27",
      packing: "60 kg jute",
      shelfLife: null,
    },
    facets: { grade: "Grade 1", certifications: ["HACCP"], packaging: ["Jute bag"] },
    packings: [jute60, bulkLiner],
    seasonality: [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2],
    certificateIds: ["haccp-daklak"],
    documentIds: ["spec-robusta-grade-1-screen-18", "coa-sample-coffee"],
    facilityId: "dak-lak-coffee-plant",
    loadingPorts: coffeePorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    image: { kind: "product", motif: "bean", alt: "Robusta Screen 18 wet-polished beans", caption: "Product macro – Robusta S18" },
    gallery: [{ kind: "factory", alt: "Colour sorter", caption: "Factory – optical sorting" }],
    verified: false,
  },
  {
    slug: "robusta-grade-2-screen-13",
    category: "coffee",
    name: "Robusta Grade 2 – Screen 13",
    shortDescription: "Cost-efficient robusta for soluble coffee and blend fillers.",
    overview:
      "Standard Grade 2 robusta with higher defect tolerance, suited to instant coffee extraction and value blends. Offered FAQ-style or to buyer specification.",
    originIds: ["central-highlands"],
    crop: "2026/27",
    processing: ["Natural (dry)", "Cleaned"],
    grade: "Grade 2",
    spec: {
      species: "Coffea canephora (Robusta)",
      grade: "Grade 2",
      screen: "13+ (min. 90% on S13)",
      moistureMax: 13,
      foreignMatterMax: 0.5,
      blackBrokenMax: 5,
      processing: "Cleaned",
      cropYear: "2026/27",
      packing: "60 kg jute · bulk liner",
      shelfLife: null,
    },
    facets: { grade: "Grade 2", certifications: ["HACCP"], packaging: ["Jute bag", "Bulk liner"] },
    packings: [jute60, bulkLiner],
    seasonality: [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2],
    certificateIds: ["haccp-daklak"],
    documentIds: ["spec-robusta-grade-2-screen-13", "coa-sample-coffee"],
    facilityId: "dak-lak-coffee-plant",
    loadingPorts: coffeePorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    image: { kind: "product", motif: "bean", alt: "Robusta Grade 2 green beans", caption: "Product macro – Robusta G2 S13" },
    gallery: [],
    verified: false,
  },
  {
    slug: "arabica-cau-dat-washed",
    category: "coffee",
    name: "Arabica Cau Dat – Washed",
    shortDescription: "Washed Catimor Arabica from 1,500 m, selected by cup for specialty roasters.",
    overview:
      "Fully washed Arabica from farm clusters on the Cau Dat plateau, dried on raised beds and hulled to order. Lots are cupped and offered with a cupping score range — final score confirmed on pre-shipment sample.",
    originIds: ["lam-dong"],
    crop: "2026/27",
    processing: ["Washed", "Raised-bed dried"],
    grade: "Specialty",
    spec: {
      species: "Coffea arabica (Catimor)",
      grade: "Specialty / Premium",
      screen: "16+",
      moistureMax: 11.5,
      foreignMatterMax: 0,
      blackBrokenMax: 0.5,
      processing: "Fully washed",
      cropYear: "2026/27",
      packing: "60 kg jute + GrainPro",
      shelfLife: null,
    },
    facets: { grade: "Specialty", certifications: [], packaging: ["Jute bag"] },
    packings: [jute60],
    seasonality: [2, 1, 1, 1, 1, 1, 0, 0, 0, 2, 2, 2],
    certificateIds: [],
    documentIds: ["spec-arabica-cau-dat-washed", "coa-sample-coffee"],
    loadingPorts: coffeePorts,
    incoterms: ["FOB", "CIF", "DAP"],
    moq: "From 1 pallet (LCL) · 20 ft preferred",
    rfqGrades: ["Washed · 84+ cup", "Washed · 82–84 cup", "Honey process", "Natural process"],
    featured: true,
    image: { kind: "product", motif: "bean", alt: "Washed Arabica green coffee from Cau Dat", caption: "Product macro – washed Arabica" },
    gallery: [{ kind: "origin", alt: "Cau Dat plateau at dawn", caption: "Origin – Cau Dat" }],
    verified: false,
  },
  {
    slug: "fine-robusta-honey",
    category: "coffee",
    name: "Fine Robusta – Honey Processed",
    shortDescription: "Red-cherry selected robusta, honey processed for cup-driven blends.",
    overview:
      "Hand-picked ripe cherry, pulped and dried with mucilage on raised beds. A cleaner, sweeter robusta profile for specialty blends and single-origin espresso.",
    originIds: ["central-highlands", "lam-dong"],
    crop: "2026/27",
    processing: ["Honey", "Raised-bed dried"],
    grade: "Fine Robusta",
    spec: {
      species: "Coffea canephora (Robusta)",
      grade: "Fine Robusta",
      screen: "16+",
      moistureMax: 12,
      foreignMatterMax: 0,
      blackBrokenMax: 0.5,
      processing: "Honey",
      cropYear: "2026/27",
      packing: "60 kg jute + GrainPro",
      shelfLife: null,
    },
    facets: { grade: "Specialty", certifications: [], packaging: ["Jute bag"] },
    packings: [jute60],
    seasonality: [2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2],
    certificateIds: [],
    documentIds: ["spec-fine-robusta-honey"],
    loadingPorts: coffeePorts,
    incoterms: ["FOB", "CIF", "DAP"],
    moq: "From 1 pallet (LCL)",
    image: { kind: "product", motif: "cherry", alt: "Ripe red robusta cherries", caption: "Product macro – ripe cherry selection" },
    gallery: [],
    verified: false,
  },

  // ------------------------------------------------------------------ RICE
  {
    slug: "st25-fragrant-rice",
    category: "rice",
    name: "ST25 Fragrant Rice – 5% Broken",
    shortDescription: "Soft, aromatic long-grain rice from Soc Trang varieties, milled fresh per order.",
    overview:
      "ST25 grown under contract with Mekong Delta cooperatives, milled close to shipment to protect aroma. Double-polished, length-graded and colour-sorted. Available in bulk or private-label retail packs.",
    originIds: ["mekong-delta"],
    crop: "Winter–spring 2026",
    processing: ["Milled", "Double polished", "Colour sorted"],
    grade: "5% broken",
    spec: {
      variety: "ST25",
      brokenMax: 5,
      moistureMax: 14,
      grainLength: 7.0,
      chalkyMax: 3,
      purity: 95,
      milling: "Well milled, double polished",
      cropYear: "Winter–spring 2026",
      packing: "25 / 50 kg PP · 1–5 kg retail",
      shelfLife: "12 months (vacuum retail)",
    },
    facets: { grade: "5% broken", certifications: ["HACCP"], packaging: ["PP bag", "Retail / private label"] },
    packings: [pp25, pp50, retailRice],
    seasonality: [1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1],
    certificateIds: ["haccp-cantho"],
    documentIds: ["spec-st25-fragrant-rice", "coa-sample-rice"],
    facilityId: "can-tho-rice-mill",
    loadingPorts: southPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    featured: true,
    image: { kind: "product", motif: "grain", alt: "ST25 fragrant rice grains", caption: "Product macro – ST25 grains" },
    gallery: [{ kind: "factory", alt: "Rice retail packing", caption: "Packing – retail bags" }],
    verified: false,
  },
  {
    slug: "jasmine-rice-5-broken",
    category: "rice",
    name: "Jasmine Rice – 5% Broken",
    shortDescription: "Fragrant jasmine-type long grain for distributors and food service.",
    overview:
      "KDM / OM jasmine-type varieties from An Giang and Dong Thap. A reliable fragrant long grain for wholesale and food service, milled and sortexed to 5% broken.",
    originIds: ["mekong-delta"],
    crop: "Summer–autumn 2026",
    processing: ["Milled", "Polished", "Colour sorted"],
    grade: "5% broken",
    spec: {
      variety: "Jasmine (KDM / OM 18)",
      brokenMax: 5,
      moistureMax: 14,
      grainLength: 6.8,
      chalkyMax: 5,
      purity: 92,
      milling: "Well milled, polished",
      cropYear: "Summer–autumn 2026",
      packing: "25 / 50 kg PP",
      shelfLife: null,
    },
    facets: { grade: "5% broken", certifications: ["HACCP"], packaging: ["PP bag"] },
    packings: [pp25, pp50],
    seasonality: [1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1],
    certificateIds: ["haccp-cantho"],
    documentIds: ["spec-jasmine-rice-5-broken", "coa-sample-rice"],
    facilityId: "can-tho-rice-mill",
    loadingPorts: southPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    image: { kind: "product", motif: "grain", alt: "Jasmine rice grains", caption: "Product macro – jasmine rice" },
    gallery: [],
    verified: false,
  },
  {
    slug: "glutinous-rice-10-broken",
    category: "rice",
    name: "Glutinous Rice – 10% Broken",
    shortDescription: "Long-grain sticky rice for food manufacturers and Asian retail.",
    overview:
      "Long-grain glutinous rice milled to 10% broken, used by snack and dessert manufacturers and ethnic retail. Opaque white, low foreign matter.",
    originIds: ["mekong-delta"],
    crop: "Winter–spring 2026",
    processing: ["Milled", "Colour sorted"],
    grade: "10% broken",
    spec: {
      variety: "Long-grain glutinous (Nep)",
      brokenMax: 10,
      moistureMax: 14.5,
      grainLength: 6.2,
      chalkyMax: null,
      purity: 95,
      milling: "Well milled",
      cropYear: "Winter–spring 2026",
      packing: "25 / 50 kg PP",
      shelfLife: null,
    },
    facets: { grade: "10% broken", certifications: [], packaging: ["PP bag"] },
    packings: [pp25, pp50],
    seasonality: [1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1],
    certificateIds: ["haccp-cantho"],
    documentIds: ["spec-glutinous-rice-10-broken"],
    facilityId: "can-tho-rice-mill",
    loadingPorts: southPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    image: { kind: "product", motif: "grain", alt: "Glutinous rice grains", caption: "Product macro – glutinous rice" },
    gallery: [],
    verified: false,
  },

  // ------------------------------------------------------------------ CASHEW
  {
    slug: "cashew-kernels-w320",
    category: "cashew",
    name: "Cashew Kernels W320",
    shortDescription: "The most traded white whole grade — for snack packers and retailers.",
    overview:
      "White whole kernels, 300–320 per pound, graded to AFI reference and vacuum-packed in tins or bags. RCN origin is declared on every lot.",
    originIds: ["southeast-cashew-belt"],
    crop: "2026 processing",
    processing: ["Steamed & shelled", "Peeled", "Graded", "Vacuum packed"],
    grade: "W320",
    spec: {
      grade: "W320 (white wholes)",
      count: "300 – 320 kernels / lb",
      moistureMax: 5,
      brokenMax: 5,
      color: "White / pale ivory",
      standard: "AFI specification (reference)",
      packing: "Vacuum tin or bag, 2 × 11.34 kg",
      shelfLife: "12 months (vacuum)",
    },
    facets: { grade: "W320", certifications: ["BRCGS", "ISO 22000", "Kosher"], packaging: ["Vacuum tin", "Vacuum bag", "Retail / private label"] },
    packings: [cashewTin, cashewBag, cashewRetail],
    seasonality: [1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    certificateIds: ["brcgs-cashew", "iso22000-cashew", "kosher-cashew"],
    documentIds: ["spec-cashew-kernels-w320", "coa-sample-cashew", "cert-brcgs-cashew"],
    facilityId: "binh-phuoc-cashew-plant",
    loadingPorts: southPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container (≈ 700 cartons)",
    featured: true,
    image: { kind: "product", motif: "kernel", alt: "W320 white whole cashew kernels", caption: "Product macro – W320 kernels" },
    gallery: [{ kind: "factory", alt: "Cashew vacuum packing", caption: "Packing – vacuum tins" }],
    verified: false,
  },
  {
    slug: "cashew-kernels-w240",
    category: "cashew",
    name: "Cashew Kernels W240",
    shortDescription: "Large white wholes for premium retail and gifting.",
    overview:
      "Larger-count white wholes (220–240 per pound) selected for premium snack and gifting ranges. Same processing and packing controls as W320.",
    originIds: ["southeast-cashew-belt"],
    crop: "2026 processing",
    processing: ["Steamed & shelled", "Peeled", "Graded", "Vacuum packed"],
    grade: "W240",
    spec: {
      grade: "W240 (white wholes)",
      count: "220 – 240 kernels / lb",
      moistureMax: 5,
      brokenMax: 5,
      color: "White / pale ivory",
      standard: "AFI specification (reference)",
      packing: "Vacuum tin or bag, 2 × 11.34 kg",
      shelfLife: "12 months (vacuum)",
    },
    facets: { grade: "W240", certifications: ["BRCGS", "ISO 22000", "Kosher"], packaging: ["Vacuum tin", "Vacuum bag"] },
    packings: [cashewTin, cashewBag],
    seasonality: [1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    certificateIds: ["brcgs-cashew", "iso22000-cashew", "kosher-cashew"],
    documentIds: ["spec-cashew-kernels-w240", "coa-sample-cashew"],
    facilityId: "binh-phuoc-cashew-plant",
    loadingPorts: southPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    image: { kind: "product", motif: "kernel", alt: "W240 cashew kernels", caption: "Product macro – W240 kernels" },
    gallery: [],
    verified: false,
  },
  {
    slug: "cashew-splits-ws",
    category: "cashew",
    name: "Cashew Splits WS",
    shortDescription: "White splits for bakery, confectionery and ingredient use.",
    overview:
      "Naturally split white kernels — the cost-efficient choice when whole-kernel appearance isn't required. Popular with bakery, cereal and confectionery manufacturers.",
    originIds: ["southeast-cashew-belt"],
    crop: "2026 processing",
    processing: ["Steamed & shelled", "Peeled", "Graded", "Vacuum packed"],
    grade: "WS",
    spec: {
      grade: "WS (white splits)",
      count: "—",
      moistureMax: 5,
      brokenMax: 5,
      color: "White / pale ivory",
      standard: "AFI specification (reference)",
      packing: "Vacuum bag, 2 × 11.34 kg",
      shelfLife: "12 months (vacuum)",
    },
    facets: { grade: "WS / Pieces", certifications: ["BRCGS", "ISO 22000"], packaging: ["Vacuum bag"] },
    packings: [cashewBag],
    seasonality: [1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    certificateIds: ["brcgs-cashew", "iso22000-cashew"],
    documentIds: ["spec-cashew-splits-ws"],
    facilityId: "binh-phuoc-cashew-plant",
    loadingPorts: southPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    image: { kind: "product", motif: "kernel", alt: "White split cashew kernels", caption: "Product macro – WS splits" },
    gallery: [],
    verified: false,
  },

  // ------------------------------------------------------------------ PEPPER
  {
    slug: "black-pepper-550gl",
    category: "pepper",
    name: "Black Pepper 550 g/l – Cleaned",
    shortDescription: "Machine-cleaned black pepper for grinders and spice packers.",
    overview:
      "Black pepper from Gia Lai and Dak Lak, machine-cleaned and graded to 550 g/l bulk density. Steam sterilisation available on request for buyers with microbiological limits.",
    originIds: ["central-highlands", "southeast-cashew-belt"],
    crop: "2026",
    processing: ["Sun-dried", "Machine cleaned", "Steam sterilised (option)"],
    grade: "550 g/l",
    spec: {
      type: "Black pepper, whole",
      density: 550,
      moistureMax: 13,
      extraneousMax: 0.5,
      lightBerriesMax: 2,
      processing: "Machine cleaned",
      micro: "Per buyer spec (sterilised option)",
      packing: "25 / 50 kg PP",
    },
    facets: { grade: "550 g/l", certifications: ["HACCP", "Halal"], packaging: ["PP bag"] },
    packings: [pepperBag, bigBag],
    seasonality: [1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    certificateIds: ["haccp-daklak", "halal-daklak"],
    documentIds: ["spec-black-pepper-550gl", "coa-sample-pepper"],
    facilityId: "dak-lak-coffee-plant",
    loadingPorts: southPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    featured: true,
    image: { kind: "product", motif: "peppercorn", alt: "Black pepper 550 g/l", caption: "Product macro – black pepper" },
    gallery: [],
    verified: false,
  },
  {
    slug: "white-pepper-630gl",
    category: "pepper",
    name: "White Pepper 630 g/l",
    shortDescription: "Double-washed white pepper for sauces, seasoning and retail.",
    overview:
      "Retted and double-washed white pepper with a clean, pale surface. Graded to 630 g/l and dried to low moisture for stable ocean freight.",
    originIds: ["central-highlands"],
    crop: "2026",
    processing: ["Retted", "Double washed", "Sun-dried"],
    grade: "630 g/l",
    spec: {
      type: "White pepper, whole",
      density: 630,
      moistureMax: 13,
      extraneousMax: 0.2,
      lightBerriesMax: null,
      processing: "Double washed",
      micro: "Per buyer spec",
      packing: "25 / 50 kg PP",
    },
    facets: { grade: "630 g/l", certifications: ["HACCP"], packaging: ["PP bag"] },
    packings: [pepperBag],
    seasonality: [1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    certificateIds: ["haccp-daklak"],
    documentIds: ["spec-white-pepper-630gl"],
    facilityId: "dak-lak-coffee-plant",
    loadingPorts: southPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    image: { kind: "product", motif: "peppercorn", alt: "White pepper 630 g/l", caption: "Product macro – white pepper" },
    gallery: [],
    verified: false,
  },

  // ------------------------------------------------------------------ FRUITS
  {
    slug: "white-flesh-dragon-fruit",
    category: "fruits",
    name: "White-Flesh Dragon Fruit – Fresh",
    shortDescription: "Fresh Binh Thuan dragon fruit, graded by count and pre-cooled for reefer.",
    overview:
      "Fresh white-flesh dragon fruit (Binh Thuan variety) from registered growing areas. Washed, graded by weight and pre-cooled at the packhouse. Destination-specific requirements (e.g. irradiation or vapour heat treatment) are confirmed per market before contract.",
    originIds: ["binh-thuan-coast"],
    crop: "2026 season",
    processing: ["Packhouse washed", "Graded", "Pre-cooled"],
    spec: {
      variety: "Binh Thuan white-flesh (Hylocereus undatus)",
      sizeCount: "300 – 600 g / fruit · 8–16 per 5 kg carton",
      brixMin: 12,
      storageTemp: "5 – 8 °C",
      shelfLife: "25 – 30 days at 5 °C",
      season: "Year-round, peak May – Aug",
      treatment: "Market-dependent (VHT / irradiation)",
      packing: "5 kg ventilated carton",
    },
    facets: { certifications: ["GLOBALG.A.P."], packaging: ["Carton"], availability: "Year-round" },
    packings: [fruitCarton],
    seasonality: [1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1],
    certificateIds: ["globalgap-dragonfruit"],
    documentIds: ["spec-white-flesh-dragon-fruit", "cert-globalgap-dragonfruit"],
    loadingPorts: ["Cat Lai (Ho Chi Minh City)", "Tan Son Nhat (air)"],
    incoterms: ["FOB", "CFR", "CIF", "CPT (air)"],
    moq: "1 × 40 ft reefer · air freight from 1 pallet",
    featured: true,
    image: { kind: "product", motif: "fruit", alt: "Fresh white-flesh dragon fruit", caption: "Product macro – dragon fruit" },
    gallery: [{ kind: "origin", alt: "Dragon fruit farms", caption: "Origin – Binh Thuan" }],
    verified: false,
  },
  {
    slug: "cat-chu-mango",
    category: "fruits",
    name: "Cat Chu Mango – Fresh",
    shortDescription: "Sweet, fibre-free mango from Dong Thap for Asian and Middle East markets.",
    overview:
      "Cat Chu mango from Dong Thap orchards, harvested at mature-green stage for sea freight. Eligibility and treatment vary by destination — confirmed per market.",
    originIds: ["mekong-delta"],
    crop: "2026 season",
    processing: ["Hot-water treated", "Graded", "Pre-cooled"],
    spec: {
      variety: "Cat Chu",
      sizeCount: "250 – 400 g / fruit",
      brixMin: 14,
      storageTemp: "10 – 13 °C",
      shelfLife: "18 – 21 days",
      season: "Mar – Jun (main), Oct – Dec (off-season)",
      treatment: "Hot-water / VHT per market",
      packing: "5 kg carton",
    },
    facets: { certifications: [], packaging: ["Carton"], availability: "Seasonal" },
    packings: [fruitCarton],
    seasonality: [0, 0, 2, 2, 2, 2, 1, 0, 0, 1, 1, 1],
    certificateIds: [],
    documentIds: ["spec-cat-chu-mango"],
    loadingPorts: ["Cat Lai (Ho Chi Minh City)"],
    incoterms: ["FOB", "CFR"],
    moq: "1 × 40 ft reefer",
    image: { kind: "product", motif: "fruit", alt: "Cat Chu mango", caption: "Product macro – Cat Chu mango" },
    gallery: [],
    verified: false,
  },
  {
    slug: "frozen-durian-ri6",
    category: "fruits",
    name: "Frozen Durian Ri6 – Whole & Pulp",
    shortDescription: "Blast-frozen Ri6 durian, whole fruit or vacuum-packed pulp.",
    overview:
      "Ri6 durian harvested at full maturity and blast-frozen (-35 °C core) as whole fruit or vacuum-packed pulp. Suitable for food service and dessert manufacturers.",
    originIds: ["mekong-delta", "central-highlands"],
    crop: "2026 season",
    processing: ["Blast frozen", "Vacuum packed (pulp)"],
    spec: {
      variety: "Ri6",
      sizeCount: "Whole 2 – 4 kg · pulp 400 g packs",
      brixMin: 28,
      storageTemp: "≤ -18 °C",
      shelfLife: "24 months frozen",
      season: "Year-round from frozen stock",
      treatment: "Blast frozen",
      packing: "10 kg master carton",
    },
    facets: { certifications: [], packaging: ["Frozen carton"], availability: "Year-round" },
    packings: [frozenCarton],
    seasonality: [1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1],
    certificateIds: [],
    documentIds: ["spec-frozen-durian-ri6"],
    loadingPorts: ["Cat Lai (Ho Chi Minh City)"],
    incoterms: ["FOB", "CFR", "CIF"],
    moq: "1 × 40 ft reefer",
    image: { kind: "product", motif: "fruit", alt: "Frozen durian pulp", caption: "Product macro – durian" },
    gallery: [],
    verified: false,
  },

  // ------------------------------------------------------------------ SPICES
  {
    slug: "split-cassia-cinnamon",
    category: "spices",
    name: "Split Cassia Cinnamon",
    shortDescription: "Scraped split cassia bark with high volatile oil for grinders.",
    overview:
      "Cassia bark from 10–15-year-old trees in Yen Bai, scraped and split, sun-dried and re-dried before packing. Specified by length, oil content and moisture.",
    originIds: ["northern-mountains"],
    crop: "Spring 2026",
    processing: ["Scraped", "Sun-dried", "Re-dried"],
    spec: {
      form: "Split, scraped",
      size: "30 – 45 cm, width 2 – 4 cm",
      moistureMax: 13.5,
      oilContent: 3,
      admixtureMax: 1,
      processing: "Sun-dried, scraped",
      packing: "10 kg carton / PP bag",
      shelfLife: "24 months",
    },
    facets: { certifications: [], packaging: ["Carton", "PP bag"] },
    packings: [spiceCarton],
    seasonality: [1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    certificateIds: [],
    documentIds: ["spec-split-cassia-cinnamon"],
    loadingPorts: northPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    image: { kind: "product", motif: "stick", alt: "Split cassia cinnamon bark", caption: "Product macro – split cassia" },
    gallery: [],
    verified: false,
  },
  {
    slug: "star-anise-autumn",
    category: "spices",
    name: "Star Anise – Autumn Crop",
    shortDescription: "Whole, reddish-brown star anise from Lang Son's main crop.",
    overview:
      "Autumn-crop star anise from Lang Son: larger, fuller stars with rich aroma. Graded by proportion of whole stars and dried to safe moisture.",
    originIds: ["northern-mountains"],
    crop: "Autumn 2026",
    processing: ["Sun-dried", "Hand graded"],
    spec: {
      form: "Whole stars",
      size: "≥ 2.5 cm, ≥ 80% whole",
      moistureMax: 13,
      oilContent: null,
      admixtureMax: 1,
      processing: "Sun-dried, hand graded",
      packing: "10 kg carton",
      shelfLife: "24 months",
    },
    facets: { certifications: [], packaging: ["Carton"] },
    packings: [spiceCarton],
    seasonality: [1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1],
    certificateIds: [],
    documentIds: ["spec-star-anise-autumn"],
    loadingPorts: northPorts,
    incoterms: standardTerms,
    moq: "1 × 20 ft container",
    image: { kind: "product", motif: "star", alt: "Whole star anise", caption: "Product macro – star anise" },
    gallery: [],
    verified: false,
  },
];
